name: 'ssh-action'
description: 'ssh action /w multi platform'
author: 'okky-lab'
inputs:
  host:
    required: true
    description: 'host'
  username:
    required: true
    description: 'username'
  key:
    required: true
    description: 'private key'
  port:
    description: 'port'
    default: '22'
  script:
    description: 'script'
runs:
  using: 'node20'
  main: 'dist/index.js'
